# Generated by Django 3.2 on 2022-12-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cepalstat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dato',
            name='dimensiones',
            field=models.ManyToManyField(related_name='datos', to='cepalstat.Dimension', verbose_name='Dimensiones'),
        ),
    ]
