# Generated by Django 3.2.10 on 2022-12-13 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cepalstat', '0003_alter_fuente_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dato',
            old_name='nota',
            new_name='notas',
        ),
    ]
