# Generated by Django 3.2.4 on 2023-01-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cepalstat', '0004_rename_nota_dato_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='orden',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dimension',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fuente',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fuente',
            name='sdmx',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicador',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='sdmx',
            field=models.TextField(blank=True, null=True),
        ),
    ]
